# Generated by Django 3.1 on 2020-08-25 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
                ('group_id', models.TextField(null=True)),
                ('group_domain', models.TextField(null=True)),
                ('vk_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('target_group_name', models.TextField()),
                ('target_group_link', models.TextField()),
                ('donors', models.ManyToManyField(to='posts.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField()),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('reposts_count', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('img_links', models.TextField(blank=True, null=True)),
                ('for_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.recipient')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
