# Generated by Django 3.1 on 2020-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='group_domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='group_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
