# Generated by Django 3.1 on 2020-08-29 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200826_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
