# Generated by Django 3.1 on 2020-08-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200829_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='subs_amout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='from_donor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subs_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='vk_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
