# Generated by Django 3.1 on 2020-08-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200830_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='subs_amout',
            new_name='subs_amount',
        ),
    ]
