# Generated by Django 3.1 on 2020-09-06 15:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='group_key',
            field=django_cryptography.fields.encrypt(models.CharField(default='null', max_length=200)),
            preserve_default=False,
        ),
    ]
