# Generated by Django 3.1 on 2020-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_recipient_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='target_group_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
