# Generated by Django 3.1 on 2020-09-08 21:27

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_recipient_target_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='tg_channel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='tg_token',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=30, null=True)),
        ),
    ]
