# Generated by Django 3.1 on 2020-09-08 22:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200909_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='tg_channel',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='tg_token',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=150, null=True)),
        ),
    ]
