# Generated by Django 3.1 on 2020-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200909_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='group_domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='group_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='from_donor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='target_group_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='target_group_name',
            field=models.CharField(max_length=70),
        ),
    ]
