version: '3'
    
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: celery -A GroupRunner worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A GroupRunner beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis