version: '3'
    
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: 
      .env
  celery:
    build: .
    command: celery -A borrower worker -l info
    volumes:
      - .:/code
  celery-beat:
    build: .
    command: celery -A borrower beat -l info
    volumes:
      - .:/code